title: Math + Science Club
description: In-person club at Ridgedale Library
url: https://www.mathscienceclub.org
baseurl: ""
theme: minima
default_header_image: /assets/images/group-picture.jpg

twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/group-picture.jpg

markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - math.md
  - science.md
  - events.md
  - team.md
  - register.md
  - donate.md
  - sponsors.md
